### ISSUE TITLE
Wofür?

### ISSUE THREAD

**Issue by justinb1617** [ChampOfGames/DudenAPI#1]
Wofür soll man die DudenAPI benutzen? Für Pocketmine, oder Bots oder wofür auch immer.. ? Also mir würde nix einfallen gerade

**Comment by champmq** [comment]
Ich hab es in einem Projekt genutzt und habs dann veröffentlicht also ich hatte bisher einen nutzen idk ob jmd anderes es braucht.

**Comment by justinb1617** [comment]
Meinst du man könnte sowas für Pocketmine benutzen?

**Comment by champmq** [comment]
Du kannst es überall wo du PHP nutzt das hier benutzen
